#该配置用户部署环境，会被复制到部署镜像中作为高于Default配置的高一级基线配置。
#同时作为运维人员对配置中心的配置项的参考

#========== SuperAdmin ==========#
superadmin:
  username: admin
  passwd: 123456

#========== Service ==========#
svc:
  baseDomain: core.cyan.org.cn
  ucenter: http://core.cyan.org.cn/ucenter

#========== JDBC ==========#
database:
  password: nazgul
  url: jdbc:mysql://rm-wz9k4pu4q2op9l984eo.mysql.rds.aliyuncs.com:3306/nazgul?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
  user: nazgul

#========== LOG LEVEL ==========#
logging:
  level: INFO
