-- auto Generated on 2017-12-27 10:30:53 
-- DROP TABLE IF EXISTS naz_person; 
CREATE TABLE naz_person(
	person_id VARCHAR (64) UNIQUE NOT NULL DEFAULT -1 COMMENT 'Person ID',
	name VARCHAR (64) DEFAULT '' COMMENT 'Person Name',
	id BIGINT (64) NOT NULL AUTO_INCREMENT COMMENT '逻辑主键',
	ts_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间戳 DEFAULT CURRENT_TIMESTAMP',
	ts_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间戳 DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
	age INT(11) DEFAULT -1 COMMENT 'age',
	gender INT(11) DEFAULT -1 COMMENT 'gender',
  first_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'firstName',
  last_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'lastName',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'naz_person';

INSERT INTO `naz_person` VALUES (1, 'Who', 1, '2017-12-27 17:35:06', '2017-12-31 13:03:08', 15, 0, 'tony', 'Chen');
INSERT INTO `naz_person` VALUES (2, 'Destroyer', 2, '2017-12-27 17:35:17', '2017-12-31 13:03:03', 21, 0, 'tom', 'Chow');
INSERT INTO `naz_person` VALUES (3, 'Winner', 4, '2017-12-27 17:35:48', '2017-12-31 13:02:56', 18, 1, 'tiffany', 'Chen');
INSERT INTO `naz_person` VALUES (4, 'Rubby', 5, '2017-12-31 12:44:46', '2017-12-31 13:02:48', 8, 0, 'jerry', 'King');
-- auto Generated on 2018-01-10 21:48:39 
-- DROP TABLE IF EXISTS person; 
CREATE TABLE person(
	person_id VARCHAR (64) UNIQUE NOT NULL DEFAULT '' COMMENT 'Person ID
     * Warning ! : If you want to use duplicated primary key, Should not use the ID Generator. Use composit-Ids instead.',
	name VARCHAR (64) DEFAULT '' COMMENT 'Person Name',
	age INT (11) DEFAULT -1 COMMENT '年龄',
	gender INT (11) DEFAULT -1 COMMENT '性别 0-男 1-女',
	first_name VARCHAR (64) DEFAULT '' COMMENT '名',
	last_name VARCHAR (6450) DEFAULT '' COMMENT '姓',
	id BIGINT (15) UNIQUE NOT NULL AUTO_INCREMENT COMMENT '逻辑主键',
	ts_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间戳 DEFAULT CURRENT_TIMESTAMP',
	ts_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间戳 DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'person';
-- auto Generated on 2018-01-10 22:20:46 
-- DROP TABLE IF EXISTS person; 
CREATE TABLE person(
	person_id VARCHAR (64) UNIQUE NOT NULL DEFAULT '' COMMENT '业务主键',
	name VARCHAR (64) DEFAULT '' COMMENT '用户姓名',
	age INT (11) DEFAULT -1 COMMENT '年龄',
	gender INT (11) DEFAULT -1 COMMENT '性别 0-男 1-女',
	first_name VARCHAR (64) DEFAULT '' COMMENT '名',
	last_name VARCHAR (64) DEFAULT '' COMMENT '姓',
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '逻辑主键',
	ts_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间戳 DEFAULT CURRENT_TIMESTAMP',
	ts_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间戳 DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
	item_stat INT (11) NOT NULL DEFAULT 1 COMMENT '记录状态，伪删除等使用，1为有效， 0为无效
     *
     * @return',
	INDEX(item_stat),
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'person';
-- auto Generated on 2018-01-10 22:22:38 
-- DROP TABLE IF EXISTS naz_person; 
CREATE TABLE naz_person(
	person_id VARCHAR (64) UNIQUE NOT NULL DEFAULT '' COMMENT 'Person ID',
	name VARCHAR (64) DEFAULT '' COMMENT 'Person Name',
	age INT (11) DEFAULT -1 COMMENT '年龄',
	gender INT (11) DEFAULT -1 COMMENT '性别 0-男 1-女',
	first_name VARCHAR (64) DEFAULT '' COMMENT '名',
	last_name VARCHAR (64) DEFAULT '' COMMENT '姓',
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '逻辑主键',
	ts_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间戳 DEFAULT CURRENT_TIMESTAMP',
	ts_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间戳 DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
	item_stat INT (11) NOT NULL DEFAULT 1 COMMENT '记录状态，伪删除等使用，1为有效， 0为无效
     *
     * @return',
	INDEX(person_id),
	INDEX(item_stat),
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'naz_person';
