-- auto Generated on 2018-01-02 14:35:23 
-- DROP TABLE IF EXISTS super_admin; 
CREATE TABLE naz_super_admin(
	username VARCHAR (64) NOT NULL DEFAULT '' COMMENT '超级管理员用户名',
	password VARCHAR (50) DEFAULT '' COMMENT '超级管理员密码',
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT '逻辑主键',
	ts_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间戳 DEFAULT CURRENT_TIMESTAMP',
	ts_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间戳 DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'super_admin';
